quarkus.profile=dev

quarkus.rest-client.apisparatestes.url=https://apisparatestes-ecru.vercel.app/


quarkus.http.port=9000

%dev.quarkus.datasource.db-kind=mysql
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/emprestimo?createDatabaseIfNotExist=true

%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.log.sql=true

quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG